// Deployed contract addresses on Stellar Testnet
export const STAKED_POLL_ID = 'CCGMIHJBNDRICJXHA64Y7KIGL6L5VCY5LR6USZRUD5MCJE5QPZIVAXUD'
export const VOTE_TOKEN_ID  = 'CALJYXH3VYMYBMD4GVHM74UO5FKO7DZQ2IA2IB6NQTEXTUAEZOPT4ZL5'